jvm_binary(
    name = "new-target-name",
    basename = "bsp",
    main = "bsp.issue.Issue",
    source = "Main.scala",
    dependencies = [
        "src/main/resources/bsp:bsp",
        "3rdparty/jvm/org/scala-lang:scala-library",
    ],
)

