jvm_binary(
    name = "bin",
    basename = "bsp",
    main = "bsp.Main",
    source = "Main.scala",
    dependencies = [
        "src/main/resources/bsp:bsp",
        "3rdparty/jvm/org/scala-lang:scala-library",
    ],
)

